from pathlib import Path

BUILD = Path("_build")

rule all:
    input:
        expand(BUILD / "{docname}.pdf", docname=["quasisep"])

rule tex:
    input:
        "doc/{docname}.md",
        "doc/{docname}.bib",
        "doc/figures/demo.pdf",
    output:
        BUILD / "{docname}.tex"
    params:
        build_dir = BUILD
    shell:
        """
        myst build {input[0]} --tex
        cp -r doc/_build/exports/{wildcards.docname}_tex/* {params.build_dir}/
        """

rule pdf:
    input:
        BUILD / "{docname}.tex"
    output:
        BUILD / "{docname}.pdf"
    shell:
        """
        tectonic {input} --keep-logs --keep-intermediates
        """

rule figure:
    input:
        "scripts/demo.py"
    output:
        "doc/figures/demo.pdf"
    shell:
        "python {input} {output}"