name: article

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: _build
          key: build-${{ hashFiles('pixi.lock') }}
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.17.1
          cache: true
      - run: pixi run build
